config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about', as: 'about'
  post '/users/:id' => 'users#create'
  get '/search', to: 'searches#search'
  
  resources :users, only: [:index, :create, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end


  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

  
  attachment :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)
    if current_user
      flash[:notice]
      user_path(current_user.id)
    else
      flash[:notice]
      user_path(current_user.id)
    end
  end

  def after_sign_out_path_for(resource)
      flash[:notice] = "Signed out successfully."
      root_path
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, {only: [:edit]}

  def ensure_current_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
       redirect_to books_path
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] = "Book was successfully created."
       redirect_to book_path(@book)
    else
       flash.now[:alert]
       @books = Book.all
       render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
       redirect_to book_path
    else
      flash.now[:alert]
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.user_id = current_user.id
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    session[:previous_url] = request.referer 
    redirect_to session[:previous_url]
   
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    session[:previous_url] = request.referer 
    redirect_to session[:previous_url]
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
 # ——————フォロー機能を作成・保存・削除する————————————
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
  #————————フォロー・フォロワー一覧を表示する-————————————
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  
  def search
    # viewのform_tagにて
    # 選択したmodelの値を@modelに代入。
    @model = params["model"]
    # 選択した検索方法の値を@methodに代入。
    @method = params["method"]
    # 検索ワードを@contentに代入。
    @content = params["content"]
    # @model, @content, @methodを代入した、
    # search_forを@recordsに代入。
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    # 選択したモデルがuserだったら
    if model == 'user'
      # 選択した検索方法がが完全一致だったら
      if method == 'perfect'
        User.where(name: content)
      # 選択した検索方法がが部分一致だったら
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    # 選択したモデルがpostだったら
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, {only: [:edit]}

  def ensure_current_user
    @user = User.find(params[:id])
    unless @user == current_user
       redirect_to user_path(current_user.id)
    end
  end

  def index
    @users = User.all
    @books = Book.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    @user.id = current_user.id
  end

  def update
    @user = User.find(params[:id])
    @user.id = current_user.id
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
      flash.now[:alert]
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book,book.id), method: :delete, remote: true do %>
    <i class="fas fa-heart unlike-btn">
      <%= book.favorites.count %>
    </i>
    <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="far fa-heart like-btn">
      <%= book.favorites.count %>
    </i>
  <% end %>
<% end %>

app/views/books/_index.html.erb
      <table class="table table-hover table-inverse">

        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                <%=  attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
              <td><%= book.body %></td>
              <td>
                <%= render 'books/favorite', book: book %>
              </td>
              <td>コメント数:<%= book.book_comments.count %></td>
          <% end %>
        </tbody>

      </table>

app/views/books/_list.html.erb
<% if book.errors.any? %>
       <div id="error_explanation">
         <h2><%= book.errors.count %>errors prohibited this book from being saved:</h2>
           <ul>
             <% book.errors.full_messages.each do |message| %>
               <li><%= message %></li>
             <% end %>
           </ul>
        </div>
       <% end %>

      <h2>User info</h2>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
            </tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
            <tr>
    <th>follows</th>
    <th>
      <% if user != current_user %>
        <%= link_to current_user.followers.count, user_followings_path(user.id) %>
      <% else %>
        <%= link_to current_user.followings.count, user_followings_path(user.id) %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <% if user != current_user %>
        <%= link_to current_user.followings.count, user_followers_path(user.id) %>
      <% else %>
        <%= link_to current_user.followers.count, user_followers_path(user.id) %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>
    <% if user != current_user %>
      <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-success text-light" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success text-light" %>
      <% end %>
    <% end %>
    </th>
  </tr>
          </tbody>
        </table>

        <p><%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %></p>

        <h2 class="mt-3">New book</h2>
          <%= form_with model:book, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class: "form-control book_title" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class: "form-control book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class: "btn btn-success" %>
          </div>
        <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <p id="notice"><%= flash[:notice] %></p>

      <h2>Editing Book</h2>

      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_body">Opinion</label>
          <%= f.text_area :body, rows:'2', class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>

      <%= link_to "Show", book_path, class: "show_#{@book.id}" %>
      |
      <%= link_to "Back", books_path, class: "Back" %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"><%= flash[:notice] %></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <%= render 'books/list', book: @book, user: current_user %>

    </div>

    <div class="col-md-8 offset-md-1">
      
      <%= render 'searches/form' %>

      <h2>Books</h2>

      <%= render 'index', books: @books %>

    </div>

  </div>
</div>

app/views/books/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <%= render 'books/list', book: @newbook, user: @user %>

    </div>

    <div class="col-md-8 offset-md-1">

      <table class="table table-hover table-inverse">
        <h2>Book detail</h2>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%=  attachment_image_tag @book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
              <% end %>
              <br>
              <%= link_to @user.name, user_path(@user.id) %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book), class: "show_#{@book.id}" %>
            </td>
            <td><%= @book.body %></td>
              <% if @book.user_id == current_user.id %>
                 <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
                 <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-sm btn-danger" %></td>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
        <% @book.book_comments.each do |book_comment| %>
          <p><%= attachment_image_tag(@book.user, :profile_image, :fill, 60, 60, fallback: 'no_image.jpg') %>
            <span><%= book_comment.user.name %>
              <% if book_comment.user == current_user %>
                <%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger" %>
          <% end %>
            </span>
          </p>
          <p><%= book_comment.comment %></p>
          <% end %>
          <%= form_with(model:[@book, @book_comment], local:true) do |f| %>
            <%= f.text_area :comment, class: "w-100 h-50px comment_text", :size=>"60" %>
            <%= f.submit "送信" %>
          <% end %>
    </div>

  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In<i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg", size: "40x40" %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <%= link_to users_path(user.id) do %>
            Show
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg", size: "40x40" %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <%= link_to user_path(user.id) do %>
            Show
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/searches/_form.html.erb
<% if user_signed_in? %>
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag 'content' %>
      <%= select_tag 'model', options_for_select({ "User" => "user", "Book" => "book" }) %>
      <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "部分一致" => "partial" }) %>
      <%= submit_tag '検索' %>
    <% end %>
<% end %>

app/views/searches/search.html.erb
  <%= render 'searches/form' %>

<% if @model == 'user' %>
  <h3>Users search for "<%= @content %>"</h3>
  <%= render 'users/index', users: @records %>
<% else @model == 'books' %>
  <h3>Books search for "<%= @content %>"</h3>
    <%= render 'books/index', books: @records %>
<% end %>

app/views/users/_index.html.erb
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                
                <td>フォロー数: <%= user.followings.count %></td>
                <td>フォロワー数: <%= user.followers.count %></td>
                <% if user != current_user %>
                <% if current_user.following?(user) %>
                  <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></td>
                <% else %>
                  <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
                <% end %>
                <% else %>
                <td></td>
                <% end %>
                </td>
                
                <td><%= link_to "Show", user_path(user.id) %></td>
            <% end %>
          </tbody>
        </table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <p id="notice"><%= flash[:notice] %></p>

      <h2>User info</h2>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
      <% end %>

      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, id:"user_name", class: "form-control name" %>
        </div>
        <div class="form-group">
          <label for="inputImage">Image</label>
          <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, rows:'2', autofocus: true, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= flash[:notice] %></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <%= render 'books/list', book: @book, user: current_user %>

    </div>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
          <%= render 'index',users: @users %>
      </div>

  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <%= render 'books/list', book: @book, user: @user %>
      
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
             <th>Title</th>
            <th>Opinion</th>
             <th colspan="3"></th>
          </tr>
         </thead>
    
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %></td>
              <% end %>
            <td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
            <td><%= book.body %></td>
            <td>
              <%= render 'books/favorite', book: book %>
            </td>
            <td>コメント数：<%= @book.book_comments.count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
        
  </div>
</div>